#if not defined FRONGE_HPP
#define FRONGE_HPP

#include "Application.hpp"
#include "Audio/Audio.hpp"
#include "Core.hpp"
#include "ECS/Components/Component.hpp"
#include "ECS/Components/Sprite.hpp"
#include "ECS/Components/SpriteAnimator.hpp"
#include "ECS/Components/Transform/Transform.hpp"
#include "ECS/Entity/Entity.hpp"
#include "ECS/Group.hpp"
#include "ECS/Scene/SceneManager/SceneManager.h"
#include "ECS/Systems/PhysicsSystem/PhysicsSystem.hpp"
#include "ECS/Systems/SpriteSystem/SpriteSystem.hpp"
#include "ECS/Systems/SpriteAnimatorSystem/SpriteAnimatorSystem.hpp"
#include "Events/Systems/Event.hpp"
#include "Events/Systems/EventListener.hpp"
#include "Events/Systems/UniqueEventQueue.hpp"
#include "Gamepad/Gamepad.hpp"
#include "InputManager/InputManager.hpp"
#include "Logger/Logger.hpp"
#include "SystemEventManager/SystemEventManager.hpp"
#include "Maths/MathFunctions.hpp"
#include "Maths/Structs/Chain.hpp"
#include "Maths/Structs/Circle.hpp"
#include "Maths/Structs/Polygon.hpp"
#include "Maths/Structs/Rectangle.hpp"
#include "Maths/Structs/TransformMatrix/TransformMatrix3x3.hpp"
#include "Reference/Reference.hpp"
#include "Renderer/Renderer.hpp"
#include "ResourceManager/ResourceManager.hpp"
#include "Resources/Font/Font.hpp"
#include "Resources/Music/Music.hpp"
#include "Resources/SoundEffect/SoundEffect.hpp"
#include "Resources/SpriteAnimation.hpp"
#include "Resources/Surface/Surface.hpp"
#include "Resources/Texture/Texture.hpp"
#include "Utility/CustomUniquePointer.hpp"
#include "Utility/LazyHasher.hpp"
#include "Utility/SparseSet.hpp"
#include "Utility/VariantVisitor.hpp"
#include "Window/Window.hpp"

#endif