#if not defined FRONGE_HPP
#define FRONGE_HPP

#include "Application.hpp"
#include "Audio/Audio.hpp"
#include "ECS/Components/Component.hpp"
#include "Core.hpp"
#include "ECS/Entity/Entity.hpp"
#include "ECS/Group.hpp"
#include "Events/Systems/Event.hpp"
#include "Events/Systems/EventListener.hpp"
#include "Events/Systems/UniqueEventQueue.hpp"
#include "Gamepad/Gamepad.hpp"
#include "InputManager/InputManager.hpp"
#include "Logger/Logger.hpp"
#include "SystemEventManager/SystemEventManager.hpp"
#include "Maths/MathFunctions.hpp"
#include "Reference/Reference.hpp"
#include "Renderer/Renderer.hpp"
#include "ResourceManager/ResourceManager.hpp"
#include "Resources/Font.hpp"
#include "Resources/Music.hpp"
#include "Resources/SoundEffect.hpp"
#include "Resources/Surface.hpp"
#include "Resources/Texture.hpp"
#include "Utility/CustomUniquePointer.hpp"
#include "Utility/LazyHasher.hpp"
#include "Utility/SparseSet.hpp"
#include "Utility/VariantVisitor.hpp"
#include "Window/Window.hpp"

#endif