name: MSBuild

on:
  push:
    branches: [ "main", "huge-refactor" ]
  pull_request:
    branches: [ "main", "huge-refactor" ]

env:
  solution-path: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release, Distribute]
        platform: [x64, Win32]

    steps:
    - name: Clone repository to runner
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build solution with Premake
      run: ${{ github.workspace }}\build.bat

    - name: Build program
      working-directory: ${{ github.workspace }}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{ env.solution-path }}