name: MSBuild

on:
  push:
    branches: [ "main", "huge-refactor" ]
  pull_request:
    branches: [ "main", "huge-refactor" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
 build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release, Distribute]
        BUILD_PLATFORM: [x64, Win32]

    steps:
    - uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}